### ISSUE TITLE
[BUG] something is still wrong with PCA alignment in qm7 loader

### ISSUE THREAD

**Issue by eickenberg** [CheML/CheML#12]
Somehow the alignment, which is supposed to avoid taking into account dummy atoms, does something that is neither fully taking them into account nor not taking them into account. I don't understand what it is doing yet:

![screenshot from 2016-11-06 12 00 41](https://cloud.githubusercontent.com/assets/1306635/20037019/ab16dff0-a418-11e6-995d-dc57cbf3ab6c.png)

Code is

![screenshot from 2016-11-06 12 01 50](https://cloud.githubusercontent.com/assets/1306635/20037032/d45acb92-a418-11e6-807f-dceab24260f9.png)

@SamKChang do you have any idea what could be going wrong? (I think I properly checked my installation and am running the proper up-to-date code. But if you can't reproduce, then it must be something weird on my end)

**Comment by SamKChang** [comment]
So I run the code above using the position variable generated by 'load_qm7' function. If I specify the key word 'align=False' (which is the default), then I get exactly the same result as you have posted. But if I set 'align=True', then the three outputs are exactly the same as bb (the middle one). 

I might be misunderstand something, but I think this is what we should be expecting. Because pca is taking all atoms (dummy included). The dummy atom fix will only be switched on when 'align=True'.

**Comment by eickenberg** [comment]
Hm OK, I'll check that. You are most probably right. I am just surprised because I would suspect the PCA including dummies to be in between the non-aligned version and the correctly aligned version. In any case, I couldn't find any problem with the code.

**Comment by eickenberg** [comment]
You are entirely right. Closing this.
